# docker-compose.yml - VERSÃO CORRIGIDA
version: '3.8'

services:
  # --- GITEA ---
  gitea:
    image: gitea/gitea:latest
    container_name: local_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=opal-postgres
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    networks:
      - opal_network_poc
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea_data:/data
    depends_on:
      - opal-postgres

  # --- POSTGRESQL ---
  opal-postgres:
    image: postgres:14-alpine
    container_name: opal_postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - opal_postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - opal_network_poc

  # --- REDIS ---
  opal-redis:
    image: redis:6.2-alpine
    container_name: opal_redis
    ports:
      - "6379:6379"
    networks:
      - opal_network_poc

  # --- OPAL SERVER (CONFIGURAÇÃO CORRIGIDA) ---
  opal-server:
    image: permitio/opal-server:latest
    container_name: opal_server
    depends_on:
      - opal-redis
      - opal-postgres
      - gitea
    ports:
      - "7002:7002"
    environment:
      # ✅ CORREÇÃO: Habilitar scopes
      - OPAL_SCOPES=1
      
      # ✅ CORREÇÃO: URL correta do Redis (nome do serviço)
      - OPAL_BROADCAST_URI=redis://opal-redis:6379/0
      - OPAL_REDIS_URL=redis://opal-redis:6379/0
      
      # Banco de dados
      - OPAL_DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@opal-postgres:5432/opal
      
      # Autenticação
      - OPAL_AUTH_MASTER_TOKEN=8c802a9c26f5b7fbbbc59d94f249f3ba5531e9a235a7aedf0083489dc55430ec
      - OPAL_AUTH_PRIVATE_KEY=-----BEGIN OPENSSH PRIVATE KEY-----_b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn_NhAAAAAwEAAQAAAgEAtS013/xdygg8dcjrknFJ9xAZYAqh1QmXAQ/E8CvnXI12nfDhPhnW_armQWfCxuV74HLr4IsUBhV1807rHuCi5Ijkp10wB9FJAZDwy8xemGx04Smczin7lptyds3_m8fo50ed3crwVPLbNzPw/B9fLeuzUF/2gb/lTYrjDZc0wLts4aHriYr7BojTypvKU/tNpY_StY0sW5OdBDeWl2K7OJjKDeHySrzfIHDRYKSzEH8daMVT5cnoANCRiuknOPPjErfWrEv+s_6uHJAEuZLH9pTr7glk9qm/PBGkNVogUtU5OLHjDyJv5OZIzlk/wleZTyJVS4DcH+wZ9JYP_KyezDQPB0b+PJiSF7ClCsSw+PeC7NDV+E3oN9WWf6VWEx1/TUk9Xocd7HP7YRzo5ae1w7b_XOSpeWlXfoRyKsJqZmB0lNNxqMOKkfuuVofgS261ZR1J+A0+9hafec6Y/HKl1rEjfyqZfF_Yoa/FZ80hD/moGHWiiyyzrUA8I3YYXGtK3sFy7QDcXR5s2aoCHH0prK/aSGOv5Zc1Srnf+_D6JU24hH2gXBmuq08/B3MddjeDCsYRLB0MTRQBZ0H7DUNZPscSPT+t12G4dQju6gaZ1G/m_m+XP5wYS3pVTp3/xcyoqVMuWWqx4m+sVkMalIhZkbODPnnbilfUQEpDHfpPQ3ZYSf09AEj_EAAAdYuPWxLLj1sSwAAAAHc3NoLXJzYQAAAgEAtS013/xdygg8dcjrknFJ9xAZYAqh1QmX_AQ/E8CvnXI12nfDhPhnWarmQWfCxuV74HLr4IsUBhV1807rHuCi5Ijkp10wB9FJAZDwy8x_emGx04Smczin7lptyds3m8fo50ed3crwVPLbNzPw/B9fLeuzUF/2gb/lTYrjDZc0wLts4a_HriYr7BojTypvKU/tNpYStY0sW5OdBDeWl2K7OJjKDeHySrzfIHDRYKSzEH8daMVT5cnoA_NCRiuknOPPjErfWrEv+s6uHJAEuZLH9pTr7glk9qm/PBGkNVogUtU5OLHjDyJv5OZIzlk/_wleZTyJVS4DcH+wZ9JYPKyezDQPB0b+PJiSF7ClCsSw+PeC7NDV+E3oN9WWf6VWEx1/TUk_9Xocd7HP7YRzo5ae1w7bXOSpeWlXfoRyKsJqZmB0lNNxqMOKkfuuVofgS261ZR1J+A0+9h_afec6Y/HKl1rEjfyqZfFYoa/FZ80hD/moGHWiiyyzrUA8I3YYXGtK3sFy7QDcXR5s2aoCH_H0prK/aSGOv5Zc1Srnf+D6JU24hH2gXBmuq08/B3MddjeDCsYRLB0MTRQBZ0H7DUNZPscS_PT+t12G4dQju6gaZ1G/mm+XP5wYS3pVTp3/xcyoqVMuWWqx4m+sVkMalIhZkbODPnnbilf_UQEpDHfpPQ3ZYSf09AEjEAAAADAQABAAACAES0XtRQOu7U3bya0z6G6JIg0Eab8Y+8ob9c_0AV12Lg/ywYM5RWsLaPuN5/rxzGxImyeuF9TDwcYkzAlifw7sS0ZuVS0NZ+Fm3aHX5jQ1I_Q+uex5I1H3WjZDPihj10e01NWr/TZ/0G1XujHlU1vl3HHooxweSlNRsJOp4aQ3589MbBpP_TVN+lb9NjF6F2dlG3amPfo70chrQlMl25Kp9FTYYjM0MFSaXfMn8wJdlxIuFqxyyCOxEoB_rFDRkTyM5+TCHzxGqbeupI8QnAcEUBZ1CuzlM9vs/ULs2unkhbJGZsCttf50fJzj02Ghgk_KPaZ4feOZ6tRWOxoBVuLo/og/RvdiChlvsX/qqdbXnqNfupgytiktHFWCnENw7mwOixGtM_IZmcMd69br11Eyg3T15qeQuB5a7oOupPm0XzA8FzRYBwkNfM4fycJotOp9bNyz6LQAuFjI_2SzDvS1Yjg7m5od3eG+BB82X/n/wXlwNYYi9TwXnuGHr0e5bfuKVnJbf5lrx3t9aOl1lJI_suQBq/c7xOqLLlB2MKI5LynxhdDVbHlrRFPEfT8B+1tZPdAazw/6G0MlEjKxzrU1Yi1BHF_r1lMhNptEj+Wu/xnY7NDKJWCA+5ZXR7kbMVomszmRwGx/w334hTRIMcCFA2t0uQ70NsReu_im0RZo46H2KcXeEKLjAAABAQDn44vT6Ip4kXETVJzcv1lwBUCE+cPJZsvxJZ+1ygCEY5Ao_tWE8rUtB/P67YGsMySKkZx9Esqh8vYlQjTScTYdCx5sV4doy7gr6qUc1K3BZ7UXy701vLW_olwQ6Rw5M+ik1LaxtkTgEo3rpqab/OAbK7o6d32yEPGNK7ElsISF1hAma3wts96oL3V5aa_n2M0XiO8YbbfSLr/3++Eyz+8f3DqdTc/eenLxh4jQtYEPbjVzX86HgQczS+Nrks9lr164E_IbKJcidhqlPdAh77x8nNFu8WyauaP7MKbMKR1bxrNSJz6dFrVGjLbQ62iJAWKbV3KjBRl8_oLHcqFKTB6Xr4XpCAAABAQDvLMz3MTYmcSyFRx2ST3KmtZ/h8bMTamhuPBTavK8uneWOyj_Xgi3wUsWGoHpd24xoOxcbH4OhD6XhRScyzUXdG5pAB6+1urpD9qJVjKkXsv2RY6SvIZ31b_oFkB8NOvkxo0/+hfcKkQCHpuuD5r1tflxF+j2Rh4UKe6whalMxY8lNXq82sWO/Az9GuETj_AhqKtjaa1X0gCfuuoxQ7RL182zU4NIKSPNuLxMwWHd7b8WSm4kgoKR6mz/1Q61nw2ANNBr_PMqe3bol5V+W9Bq01WXQpeDo7Te+t2in+f1kf3ncmcFmnrWwQqvtfpJ68oPSDVcFjPO5IN_9iLNXKIPAfWL+nAAABAQDB6/ERcefwgdoLnv0JZ/OE/rYm8KZ7GvkQpNP06PATa/YTw6Cb_kCBNHrTcrKom9ovp9dp0qrF/BgDVO37pxpJ+7KqW5c8i/hLjbr0ZJ9WPRTmTklMNQKowhB_xtTyQgiXsAJx0CVr7tJSCRVsxusn75xp/SvtTVBenLTQ/AeRJX9Kc0peX+AjeH3P0oTNHa_Ksw/y3n3OftSgTjP4+ROIlwx0TBxrBgwJThuzzhS1/0bT87rapZIl1FsF/fdjXKCgaI3q4_IZDg3O4O8KqwVXZunbv3HiPMmyDqFRfWGAdg1uBVkSyiFfY/A1wKonzlJmW52QutdWVR1Z_BSnD+9wazBpnAAAAHnBlZHJvLWNvbnRlc3NvdG9ATU0tTkItMUZLMUpCNAECAwQ=_-----END OPENSSH PRIVATE KEY-----
      - OPAL_AUTH_PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1LTXf/F3KCDx1yOuScUn3EBlgCqHVCZcBD8TwK+dcjXad8OE+GdZquZBZ8LG5XvgcuvgixQGFXXzTuse4KLkiOSnXTAH0UkBkPDLzF6YbHThKZzOKfuWm3J2zebx+jnR53dyvBU8ts3M/D8H18t67NQX/aBv+VNiuMNlzTAu2zhoeuJivsGiNPKm8pT+02lhK1jSxbk50EN5aXYrs4mMoN4fJKvN8gcNFgpLMQfx1oxVPlyegA0JGK6Sc48+MSt9asS/6zq4ckAS5ksf2lOvuCWT2qb88EaQ1WiBS1Tk4seMPIm/k5kjOWT/CV5lPIlVLgNwf7Bn0lg8rJ7MNA8HRv48mJIXsKUKxLD494Ls0NX4Teg31ZZ/pVYTHX9NST1ehx3sc/thHOjlp7XDttc5Kl5aVd+hHIqwmpmYHSU03Gow4qR+65Wh+BLbrVlHUn4DT72Fp95zpj8cqXWsSN/Kpl8Vihr8VnzSEP+agYdaKLLLOtQDwjdhhca0rewXLtANxdHmzZqgIcfSmsr9pIY6/llzVKud/4PolTbiEfaBcGa6rTz8Hcx12N4MKxhEsHQxNFAFnQfsNQ1k+xxI9P63XYbh1CO7qBpnUb+ab5c/nBhLelVOnf/FzKipUy5ZarHib6xWQxqUiFmRs4M+eduKV9RASkMd+k9DdlhJ/T0ASMQ== pedro-contessoto@MM-NB-1FK1JB4
      - AUTH_JWT_ALGORITHM=RS256
      - AUTH_JWT_AUDIENCE=opal-client
      - AUTH_JWT_ISSUER=opal-server
      
      # Logging
      - OPAL_LOG_LEVEL=INFO
    networks:
      - opal_network_poc
    restart: unless-stopped

networks:
  opal_network_poc:
    driver: bridge
    name: opal_network_poc

volumes:
  opal_postgres_data:
    driver: local
  gitea_data:
    driver: local