# docker-compose.yml - VERSÃO CORRIGIDA
version: '3.8'

services:
  # --- GITEA ---
  gitea:
    image: gitea/gitea:latest
    container_name: local_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=opal-postgres
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    networks:
      - opal_network_poc
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea_data:/data
    depends_on:
      - opal-postgres

  # --- POSTGRESQL ---
  opal-postgres:
    image: postgres:14-alpine
    container_name: opal_postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - opal_postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - opal_network_poc

  # --- REDIS ---
  opal-redis:
    image: redis:6.2-alpine
    container_name: opal_redis
    ports:
      - "6379:6379"
    networks:
      - opal_network_poc

  # --- OPAL SERVER (CONFIGURAÇÃO CORRIGIDA) ---
  opal-server:
    image: permitio/opal-server:latest
    container_name: opal_server
    depends_on:
      - opal-redis
      - opal-postgres
      - gitea
    ports:
      - "7002:7002"
    environment:
      # ✅ CORREÇÃO: Habilitar scopes
      - OPAL_SCOPES=1
      
      # ✅ CORREÇÃO: URL correta do Redis (nome do serviço)
      - OPAL_BROADCAST_URI=redis://opal-redis:6379/0
      - OPAL_REDIS_URL=redis://opal-redis:6379/0
      
      # Banco de dados
      - OPAL_DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@opal-postgres:5432/opal
      
      # Autenticação
      - OPAL_SERVER_API_KEY=${OPAL_TOKEN}
      - OPAL_SERVER_WORKER_TOKEN_PRIVATE_KEY=${OPAL_PRIVATE_KEY}
      - OPAL_SERVER_WORKER_TOKEN_PUBLIC_KEY=${OPAL_PUBLIC_KEY}
      
      # Logging
      - OPAL_LOG_LEVEL=INFO
    networks:
      - opal_network_poc
    restart: unless-stopped

networks:
  opal_network_poc:
    driver: bridge
    name: opal_network_poc

volumes:
  opal_postgres_data:
    driver: local
  gitea_data:
    driver: local