# docker-compose.yml - VERSÃO CORRIGIDA
# Removida a linha 'version' que é obsoleta
# version: '3.8'

services:
  # --- GITEA ---
  gitea:
    image: gitea/gitea:latest
    container_name: local_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=opal-postgres
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    networks:
      - opal_network_poc
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea_data:/data
    depends_on:
      - opal-postgres
    # ✅ ADICIONADO: Healthcheck para garantir que o Gitea esteja pronto antes do OPAL Server tentar usá-lo.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --- POSTGRESQL ---
  opal-postgres:
    image: postgres:14-alpine
    container_name: opal_postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - opal_postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - opal_network_poc
    # Adicionado um healthcheck simples para o postgres também, por boa prática.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d gitea"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- REDIS ---
  opal-redis:
    image: redis:6.2-alpine
    container_name: opal_redis
    ports:
      - "6379:6379"
    networks:
      - opal_network_poc
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- OPAL SERVER (CONFIGURAÇÃO CORRIGIDA ) ---
  opal-server:
    image: permitio/opal-server:latest
    container_name: opal_server
    # ✅ MODIFICADO: depends_on agora usa condições para esperar os serviços ficarem saudáveis.
    depends_on:
      opal-redis:
        condition: service_healthy
      opal-postgres:
        condition: service_healthy
      gitea:
        condition: service_healthy
    ports:
      - "7002:7002"
    environment:
      - OPAL_SCOPES=1
      - OPAL_BROADCAST_URI=redis://opal-redis:6379/0
      - OPAL_REDIS_URL=redis://opal-redis:6379/0
      - OPAL_DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@opal-postgres:5432/opal
      - OPAL_AUTH_PRIVATE_KEY=${OPAL_AUTH_PRIVATE_KEY}
      - OPAL_AUTH_PUBLIC_KEY=${OPAL_AUTH_PUBLIC_KEY}
      - OPAL_AUTH_MASTER_TOKEN=${OPAL_AUTH_MASTER_TOKEN}
      - OPAL_LOG_LEVEL=DEBUG
    networks:
      - opal_network_poc
    restart: unless-stopped

networks:
  opal_network_poc:
    driver: bridge
    name: opal_network_poc

volumes:
  opal_postgres_data:
    driver: local
  gitea_data:
    driver: local
